services:
  db:
    image: docker.io/mysql:latest
    restart: unless-stopped
    expose:
      - "3306:3306/tcp"
    networks:
      - openfsd-net
    environment:
      MYSQL_ROOT_PASSWORD: supersecretpassword
      MYSQL_DATABASE: openfsd
      MYSQL_ROOT_HOST: '%'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      start_period: 5s
      interval: 5s
      timeout: 15s
      retries: 8

  openfsd:
    image: docker.io/renorris/openfsd:latest
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "6809:6809/tcp"
      - "8080:8080/tcp"
    networks:
      - openfsd-net
    environment:
      GOMAXPROCS: 1

      DOMAIN_NAME: myopenfsdserver.com
      MYSQL_USER: root
      MYSQL_PASS: supersecretpassword
      MYSQL_NET: tcp
      MYSQL_ADDR: db:3306
      MYSQL_DBNAME: openfsd

networks:
  openfsd-net:
    driver: bridge