services:
  fsd:
    build:
      context: "."
    ports:
      - "6809:6809/tcp"
      - "9086:9086/tcp"
    volumes:
      - ./db:/openfsd/db
    environment:
      FSD_ADDR: "0.0.0.0:6809"
      HTTP_ADDR: "0.0.0.0:9086"
      HTTPS_ENABLED: false
      DATABASE_FILE: "./db/fsd.db"
      MOTD: "openfsd"
    restart: unless-stopped
