site_name: FSD Documentation
repo_url: https://github.com/renorris/openfsd
repo_name: openfsd
theme: readthedocs
nav:
  - 'index.md'
  - 'about.md'
  - 'protocol.md'
  - 'enumerations.md'
  - 'authentication-token.md'
  - 'vatsim-auth.md'
