// Command aptdat2apt converts X-Plane 12 apt.dat airports into TWRTrainer-compatible
// .apt files and prints conversion coverage stats.
//
// openfsd does not ship Global Airports apt.dat. Obtain it locally (X-Plane install,
// Scenery Gateway, or -download). See docs/xplane-airport-data.md.
//
// Primary target: X-Plane 12 Global Airports apt.dat (format 1200). Download and
// convert in one step (writes apt.dat only on this machine):
//
//	go run ./cmd/aptdat2apt -download -out generated-apt -quiet
//
// Or convert a local file:
//
//	go run ./cmd/aptdat2apt -aptdat ./xp12-aptdat/apt.dat -out generated-apt -quiet
//
// XP11 (1130 and earlier) is rejected unless -allow-legacy is set.
package main

import (
	"bufio"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/renorris/openfsd/internal/xp12aptdat"
)

func main() {
	aptdatFlag := flag.String("aptdat", "", "path to X-Plane 12 apt.dat (default: search XP12 candidates)")
	outDir := flag.String("out", "generated-apt", "output directory for .apt files")
	icaoFilter := flag.String("icao", "", "only convert this ICAO/identifier (case-insensitive)")
	minRunways := flag.Int("min-runways", 1, "skip airports with fewer land runways than this")
	writeEmpty := flag.Bool("write-empty", false, "write airports that have no convertible geometry")
	skipExisting := flag.Bool("skip-existing", false, "do not overwrite .apt files that already exist in -out")
	quiet := flag.Bool("quiet", false, "suppress per-airport lines; print summary only")
	allowLegacy := flag.Bool("allow-legacy", false, "allow apt.dat format < 1200 (X-Plane 11 / older)")

	// Download integration (internal/xp12aptdat).
	doDownload := flag.Bool("download", false, "download latest XP12 Global Airports apt.dat before converting")
	downloadDir := flag.String("download-dir", xp12aptdat.DefaultOutDir, "directory for downloaded apt.dat when -download is set (ignored if -aptdat is set)")
	branchPref := flag.String("branch", xp12aptdat.DefaultBranch, "preferred XP12 branch when -download: Final, Beta, or RSG")
	keepZip := flag.Bool("keep-zip", false, "keep apt.dat.zip after download (with -download)")
	lookupURL := flag.String("lookup", xp12aptdat.DefaultLookupURL, "server list URL (with -download)")
	flag.Parse()

	aptdat, err := resolveAPTDatWithDownload(*aptdatFlag, *doDownload, *downloadDir, *branchPref, *keepZip, *lookupURL)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(2)
	}
	if _, err := os.Stat(aptdat); err != nil {
		fmt.Fprintf(os.Stderr, "error: cannot read apt.dat: %v\n", err)
		os.Exit(1)
	}
	if err := os.MkdirAll(*outDir, 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "error: mkdir %s: %v\n", *outDir, err)
		os.Exit(1)
	}

	f, err := os.Open(aptdat)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: open apt.dat: %v\n", err)
		os.Exit(1)
	}
	defer f.Close()

	filter := strings.ToUpper(strings.TrimSpace(*icaoFilter))
	start := time.Now()

	var summary Stats
	summary.SourcePath = aptdat
	sc := bufio.NewScanner(f)
	// XP12 apt.dat can have very long linear-feature rows.
	buf := make([]byte, 0, 1024*1024)
	sc.Buffer(buf, 8*1024*1024)

	var cur *rawAirport
	versionSeen := false
	flush := func() {
		if cur == nil {
			return
		}
		if filter != "" && !airportMatchesFilter(cur, filter) {
			cur = nil
			return
		}
		summary.Seen++
		res := convertAirport(cur)
		if res.Written && res.RunwaysOut < *minRunways {
			res.Written = false
			if res.SkipReason == "" {
				res.SkipReason = "min_runways"
			}
		}
		if res.Written || (*writeEmpty && res.Text != "" && res.FileName != "") {
			path := filepath.Join(*outDir, res.FileName)
			if *skipExisting {
				if _, err := os.Stat(path); err == nil {
					res.Written = false
					res.SkipReason = "exists"
					summary.Accumulate(res)
					if !*quiet {
						printAirportLine(res)
					}
					cur = nil
					return
				}
			}
			if err := os.WriteFile(path, []byte(res.Text), 0o644); err != nil {
				fmt.Fprintf(os.Stderr, "write %s: %v\n", path, err)
				summary.WriteErrors++
				res.Written = false
				if res.SkipReason == "" {
					res.SkipReason = "write_error"
				}
			} else {
				summary.FilesWritten++
				res.Written = true
				res.SkipReason = ""
			}
		}
		summary.Accumulate(res)
		if !*quiet {
			printAirportLine(res)
		}
		cur = nil
	}

	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if line == "" || strings.HasPrefix(line, "#") || line == "I" || line == "A" {
			continue
		}
		if v := parseFileVersion(line); v > 0 {
			if !versionSeen || v > summary.FileVersion {
				summary.FileVersion = v
			}
			versionSeen = true
			continue
		}
		if isFileVersionLine(line) {
			// "Generated by WorldEditor" without a leading code — ignore.
			continue
		}
		if line == "99" {
			flush()
			continue
		}
		fields := strings.Fields(line)
		if len(fields) == 0 {
			continue
		}
		code := fields[0]
		if code == "1" || code == "16" || code == "17" {
			flush()
			cur = parseAirportHeader(fields, line)
			continue
		}
		if cur == nil {
			continue
		}
		cur.Lines = append(cur.Lines, line)
		cur.Codes[code]++
	}
	flush()
	if err := sc.Err(); err != nil {
		fmt.Fprintf(os.Stderr, "error reading apt.dat: %v\n", err)
		os.Exit(1)
	}

	// Version gate: X-Plane 12 = format 1200+.
	if summary.FileVersion > 0 && summary.FileVersion < minXP12Version && !*allowLegacy {
		fmt.Fprintf(os.Stderr,
			"error: apt.dat format %d is pre-XP12 (need ≥ %d).\n"+
				"  This converter targets X-Plane 12 Global Airports data.\n"+
				"  Download XP12 apt.dat and convert:\n"+
				"    go run ./cmd/aptdat2apt -download -out generated-apt -quiet\n"+
				"  Or re-run with -allow-legacy to force conversion of older files.\n"+
				"  source: %s\n",
			summary.FileVersion, minXP12Version, aptdat)
		os.Exit(1)
	}
	if summary.FileVersion == 0 && !*allowLegacy {
		fmt.Fprintf(os.Stderr,
			"error: could not detect apt.dat format version (expected \"1200 …\" banner).\n"+
				"  source: %s\n"+
				"  Use an X-Plane 12 apt.dat, pass -download, or pass -allow-legacy.\n", aptdat)
		os.Exit(1)
	}

	fmt.Println()
	summary.Print(os.Stdout, *outDir, time.Since(start))
}

func airportMatchesFilter(a *rawAirport, filter string) bool {
	if strings.EqualFold(a.ID, filter) {
		return true
	}
	if strings.EqualFold(a.ICAOMeta, filter) {
		return true
	}
	return false
}

func printAirportLine(r ConvertResult) {
	status := "skip"
	if r.Written {
		status = "ok"
	} else if r.SkipReason != "" {
		status = "skip:" + r.SkipReason
	}
	fmt.Printf("%-6s %-8s rwy=%d taxi=%d park=%d hold=%d nodes=%d edges=%d → %s\n",
		r.ID, status, r.RunwaysOut, r.TaxiwaysOut, r.ParkingOut, r.HoldsOut,
		r.TaxiNodesIn, r.TaxiEdgesIn, summarizeNotes(r))
}

func summarizeNotes(r ConvertResult) string {
	var parts []string
	if r.RunwaysIn > r.RunwaysOut {
		parts = append(parts, fmt.Sprintf("rwy_drop=%d", r.RunwaysIn-r.RunwaysOut))
	}
	if r.TaxiEdgesIn > 0 && r.TaxiwaysOut == 0 {
		parts = append(parts, "taxi_unmapped")
	}
	if r.UnnamedTaxiEdges > 0 {
		parts = append(parts, fmt.Sprintf("unnamed_edges=%d", r.UnnamedTaxiEdges))
	}
	if r.TaxiNameSanitized > 0 {
		parts = append(parts, fmt.Sprintf("taxi_renamed=%d", r.TaxiNameSanitized))
	}
	if r.ParkingIn > r.ParkingOut {
		parts = append(parts, fmt.Sprintf("park_drop=%d", r.ParkingIn-r.ParkingOut))
	}
	if r.ICAOOut != r.ID && r.ICAOOut != "" {
		parts = append(parts, "icao="+r.ICAOOut)
	}
	if len(parts) == 0 {
		return "-"
	}
	return strings.Join(parts, ",")
}

// Stats is aggregate conversion coverage.
type Stats struct {
	SourcePath      string
	FileVersion     int
	Seen            int
	FilesWritten    int
	WriteErrors     int
	Skipped         int
	WithRunway      int
	WithTaxiNet     int
	WithParking     int
	TotalRunwaysIn  int
	TotalRunwaysOut int
	TotalTaxiIn     int
	TotalTaxiOut    int
	TotalParkIn     int
	TotalParkOut    int
	TotalHoldsOut   int
	NoGeometry      int
	SkipReasons     map[string]int
}

func (s *Stats) Accumulate(r ConvertResult) {
	if s.SkipReasons == nil {
		s.SkipReasons = make(map[string]int)
	}
	if !r.Written {
		s.Skipped++
		reason := r.SkipReason
		if reason == "" {
			reason = "unknown"
		}
		s.SkipReasons[reason]++
	}
	if r.RunwaysOut > 0 {
		s.WithRunway++
	}
	if r.TaxiNodesIn > 0 {
		s.WithTaxiNet++
	}
	if r.ParkingOut > 0 {
		s.WithParking++
	}
	s.TotalRunwaysIn += r.RunwaysIn
	s.TotalRunwaysOut += r.RunwaysOut
	s.TotalTaxiIn += r.TaxiEdgesIn
	s.TotalTaxiOut += r.TaxiwaysOut
	s.TotalParkIn += r.ParkingIn
	s.TotalParkOut += r.ParkingOut
	s.TotalHoldsOut += r.HoldsOut
	if r.RunwaysOut == 0 && r.TaxiwaysOut == 0 && r.ParkingOut == 0 {
		s.NoGeometry++
	}
}

func (s *Stats) Print(w *os.File, outDir string, elapsed time.Duration) {
	fmt.Fprintln(w, "========== aptdat2apt summary ==========")
	fmt.Fprintf(w, "Source:                     %s\n", s.SourcePath)
	fmt.Fprintf(w, "apt.dat format:             %s", versionLabel(s.FileVersion))
	if s.FileVersion >= minXP12Version {
		fmt.Fprint(w, " (X-Plane 12+)")
	} else if s.FileVersion > 0 {
		fmt.Fprint(w, " (legacy / pre-XP12)")
	}
	fmt.Fprintln(w)
	fmt.Fprintf(w, "Airports seen:              %d\n", s.Seen)
	fmt.Fprintf(w, "Files written:              %d  → %s\n", s.FilesWritten, outDir)
	fmt.Fprintf(w, "Skipped (not written):      %d\n", s.Skipped)
	fmt.Fprintf(w, "Write errors:               %d\n", s.WriteErrors)
	fmt.Fprintf(w, "With ≥1 runway out:         %d\n", s.WithRunway)
	fmt.Fprintf(w, "With taxi network in:       %d\n", s.WithTaxiNet)
	fmt.Fprintf(w, "With ≥1 parking out:        %d\n", s.WithParking)
	fmt.Fprintf(w, "No convertible geometry:    %d\n", s.NoGeometry)
	fmt.Fprintln(w)
	fmt.Fprintf(w, "Runways  in→out:            %d → %d  (%.1f%%)\n",
		s.TotalRunwaysIn, s.TotalRunwaysOut, pct(s.TotalRunwaysOut, s.TotalRunwaysIn))
	fmt.Fprintf(w, "Taxi edges in / ways out:   %d edges → %d named polylines\n",
		s.TotalTaxiIn, s.TotalTaxiOut)
	fmt.Fprintf(w, "Parking  in→out:            %d → %d  (%.1f%%)\n",
		s.TotalParkIn, s.TotalParkOut, pct(s.TotalParkOut, s.TotalParkIn))
	fmt.Fprintf(w, "Hold points out:            %d\n", s.TotalHoldsOut)
	if len(s.SkipReasons) > 0 {
		fmt.Fprintln(w)
		fmt.Fprintln(w, "Skip reasons:")
		keys := make([]string, 0, len(s.SkipReasons))
		for k := range s.SkipReasons {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			fmt.Fprintf(w, "  %-24s %d\n", k, s.SkipReasons[k])
		}
	}
	fmt.Fprintln(w)
	fmt.Fprintf(w, "Elapsed: %s\n", elapsed.Round(time.Millisecond))
}

func pct(num, den int) float64 {
	if den == 0 {
		return 0
	}
	return 100 * float64(num) / float64(den)
}
