package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/renorris/openfsd/internal/xp12aptdat"
)

// Minimum apt.dat format version we treat as X-Plane 12.
// XP12 ships WorldEditor 1200; XP11 Global Airports was typically 1130.
const minXP12Version = 1200

// resolveAPTDat picks -aptdat if set, else the first existing XP12 candidate.
// Does not fall back to X-Plane 11 paths.
func resolveAPTDat(flagPath string) (string, error) {
	if strings.TrimSpace(flagPath) != "" {
		return flagPath, nil
	}
	for _, p := range xp12APTDatCandidates() {
		if st, err := os.Stat(p); err == nil && !st.IsDir() {
			return p, nil
		}
	}
	return "", fmt.Errorf("no X-Plane 12 apt.dat found; pass -aptdat, or download with:\n  go run ./cmd/aptdat2apt -download -out generated-apt\n\nsearched:\n  %s",
		strings.Join(xp12APTDatCandidates(), "\n  "))
}

// resolveAPTDatWithDownload optionally fetches XP12 Global Airports apt.dat first,
// then resolves the path used for conversion.
//
// When doDownload is true:
//   - if aptdatFlag is set, apt.dat is written to that path;
//   - otherwise it is written under downloadDir (default xp12-aptdat/apt.dat).
func resolveAPTDatWithDownload(aptdatFlag string, doDownload bool, downloadDir, branch string, keepZip bool, lookupURL string) (string, error) {
	if !doDownload {
		return resolveAPTDat(aptdatFlag)
	}

	aptPath, outDir := downloadTarget(aptdatFlag, downloadDir)
	res, err := xp12aptdat.Download(xp12aptdat.Options{
		OutDir:    outDir,
		AptPath:   aptPath,
		KeepZip:   keepZip,
		Branch:    branch,
		LookupURL: lookupURL,
	})
	if err != nil {
		return "", fmt.Errorf("download: %w", err)
	}
	if res == nil || res.AptPath == "" {
		return "", fmt.Errorf("download: empty apt path")
	}
	fmt.Println()
	return res.AptPath, nil
}

// downloadTarget chooses where -download writes apt.dat.
// If aptdatFlag is set, that exact path is used; otherwise downloadDir/apt.dat.
func downloadTarget(aptdatFlag, downloadDir string) (aptPath, outDir string) {
	aptPath = strings.TrimSpace(aptdatFlag)
	outDir = strings.TrimSpace(downloadDir)
	if outDir == "" {
		outDir = xp12aptdat.DefaultOutDir
	}
	if aptPath == "" {
		aptPath = filepath.Join(outDir, "apt.dat")
		return aptPath, outDir
	}
	outDir = filepath.Dir(aptPath)
	if outDir == "" {
		outDir = "."
	}
	return aptPath, outDir
}

func xp12APTDatCandidates() []string {
	home, _ := os.UserHomeDir()
	var out []string
	// Tooling default: download-xp12-aptdat output
	out = append(out,
		"xp12-aptdat/apt.dat",
		filepath.Join(".", "xp12-aptdat", "apt.dat"),
	)
	if home != "" {
		// Native / Steam / common install layouts (Global Scenery, not XP11 Custom Scenery).
		rel := filepath.Join("Global Scenery", "Global Airports", "Earth nav data", "apt.dat")
		roots := []string{
			filepath.Join(home, "X-Plane 12"),
			filepath.Join(home, "Applications", "X-Plane 12"),
			"/Applications/X-Plane 12",
			filepath.Join(home, "Library", "Application Support", "Steam", "steamapps", "common", "X-Plane 12"),
			filepath.Join(home, "Library", "Application Support", "Steam", "steamapps", "common", "X-Plane 12 Demo"),
		}
		for _, root := range roots {
			out = append(out, filepath.Join(root, rel))
		}
	}
	return out
}

// parseFileVersion extracts the apt.dat format version from a *file banner* line
// such as "1200 Generated by WorldEditor..." or "1000 Version - data cycle...".
//
// Important: bare row codes used inside airports must NOT match:
//
//	1200  → taxi-route network header
//	1000  → traffic flow
//	1050  → COM frequency
//	1100  → runway-in-use
//	1201/1202/1300/1500 → geometry / ramps / jetways
//
// Returns 0 if the line is not a version banner.
func parseFileVersion(line string) int {
	fields := strings.Fields(line)
	// Banners always have a code plus descriptive text ("Generated…", "Version…").
	if len(fields) < 2 {
		return 0
	}
	n, err := strconv.Atoi(fields[0])
	if err != nil {
		return 0
	}
	rest := strings.ToLower(strings.Join(fields[1:], " "))
	// Real banners from WED / Laminar exports.
	if strings.Contains(rest, "generated") ||
		strings.HasPrefix(rest, "version") ||
		strings.Contains(rest, "worldeditor") ||
		strings.Contains(rest, "data cycle") {
		switch n {
		case 810, 815, 850, 1000, 1050, 1100, 1130, 1200:
			return n
		default:
			if n >= 1000 && n < 1300 {
				// Future WED minor format bumps in the 12xx band.
				return n
			}
		}
	}
	return 0
}

func isFileVersionLine(line string) bool {
	return parseFileVersion(line) > 0
}

func versionLabel(v int) string {
	if v <= 0 {
		return "unknown"
	}
	return strconv.Itoa(v)
}
