package main

import (
	"strings"
	"testing"
)

// Minimal X-Plane 12 (format 1200) airport block with expanded surface codes,
// taxiway_E width class, multi-runway 1204, and heavy|jets ops on 1300.
const xp12KSEASnippet = `A
1200 Generated by WorldEditor 2.7.2-r1 / TY mode

1    433 0 0 KSEA Seattle Tacoma Intl
1302 city Seattle
1302 country USA United States
1302 icao_code KSEA
100 46.02 51 1 0.00 1 3 0 16L 47.4638283 -122.3077522 0 114 3 2 1 0 34R 47.4311753 -122.3080412 0 122 3 8 1 0
100 46.02 50 1 0.00 1 3 0 16C 47.4638301 -122.3109922 0 113 3 2 1 0 34C 47.4379481 -122.3112118 0 120 3 8 0 0
1200
1201 47.463665 -122.306311 both 0
1201 47.450343 -122.305272 both 1
1201 47.449657 -122.306273 both 2
1202 0 1 twoway taxiway_E A
1202 1 2 twoway taxiway_E A
1202 0 2 twoway runway 16L/34R
1204 departure 16L,34R
1300 47.450000 -122.300000 90.0 gate heavy|jets|turboprops A1
1301 C airline dal
1300 47.451000 -122.301000 0.0 tie_down props|helos GA Ramp 1
1301 A general_aviation
99
`

func TestXP12ParseAndConvert(t *testing.T) {
	a := loadSnippetAirport(t, xp12KSEASnippet, "KSEA")
	if a.ElevFt != 433 {
		t.Fatalf("elev = %v", a.ElevFt)
	}
	if a.ICAOMeta != "KSEA" {
		// icao_code is applied during parseGeometry
	}
	g := parseGeometry(a)
	if g.ICAO != "KSEA" {
		t.Fatalf("icao = %q", g.ICAO)
	}
	if len(g.Runways) != 2 {
		t.Fatalf("runways = %d", len(g.Runways))
	}
	// Surface type 51 must not break end parsing.
	if g.Runways[0].EndA != "16L" || g.Runways[0].EndB != "34R" {
		t.Fatalf("rwy0 ends = %s/%s", g.Runways[0].EndA, g.Runways[0].EndB)
	}
	if len(g.Nodes) != 3 {
		t.Fatalf("nodes = %d", len(g.Nodes))
	}
	// One named taxiway edge path "A" (two segments) + runway edges skipped in taxi out.
	taxiNamed := 0
	for _, e := range g.Edges {
		if e.Kind == "taxiway" && e.Name == "A" {
			taxiNamed++
		}
		if e.Kind == "runway" && e.Name != "16L/34R" {
			t.Errorf("unexpected runway edge name %q", e.Name)
		}
	}
	if taxiNamed != 2 {
		t.Fatalf("taxiway A edges = %d", taxiNamed)
	}
	if len(g.Ramps) != 2 {
		t.Fatalf("ramps = %d", len(g.Ramps))
	}
	if g.Ramps[0].Name != "A1" {
		t.Fatalf("ramp0 name = %q ops=%q", g.Ramps[0].Name, g.Ramps[0].Ops)
	}
	if !strings.Contains(g.Ramps[0].Ops, "heavy") {
		t.Fatalf("expected heavy in ops, got %q", g.Ramps[0].Ops)
	}
	if g.Ramps[1].Name != "GA Ramp 1" {
		t.Fatalf("ramp1 name = %q", g.Ramps[1].Name)
	}

	res := convertAirport(a)
	if !res.Written {
		t.Fatalf("not written: %s", res.SkipReason)
	}
	if res.RunwaysOut != 2 {
		t.Fatalf("runways out = %d", res.RunwaysOut)
	}
	if res.TaxiwaysOut < 1 {
		t.Fatalf("taxiways out = %d", res.TaxiwaysOut)
	}
	if res.ParkingOut != 2 {
		t.Fatalf("parking out = %d", res.ParkingOut)
	}
	if !strings.Contains(res.Text, "[RUNWAY 16L/34R]") {
		t.Fatalf("missing runway section:\n%s", res.Text)
	}
	if !strings.Contains(res.Text, "[TAXIWAY A]") {
		t.Fatalf("missing taxiway A:\n%s", res.Text)
	}
	if !strings.Contains(res.Text, "[PARKING A1]") {
		t.Fatalf("missing parking A1:\n%s", res.Text)
	}
	if !strings.Contains(res.Text, "[PARKING GARAMP1]") && !strings.Contains(res.Text, "GARAMP") {
		// sanitize strips spaces: "GA Ramp 1" → "GARAMP1"
		if !strings.Contains(res.Text, "GARAMP1") {
			t.Fatalf("missing sanitized GA parking:\n%s", res.Text)
		}
	}
}

func TestParseFileVersion(t *testing.T) {
	cases := map[string]int{
		"1200 Generated by WorldEditor 2.7.2-r1 / TY mode": 1200,
		"1130 Generated by WorldEditor 2.4.0r3":            1130,
		"1000 Version - data cycle 2012.03":                1000,
		"1    433 0 0 KSEA Seattle":                        0,
		"A":                                                0,
	}
	for line, want := range cases {
		if got := parseFileVersion(line); got != want {
			t.Errorf("parseFileVersion(%q)=%d want %d", line, got, want)
		}
	}
}

func TestHoldNameFromHintXP12(t *testing.T) {
	if got := holdNameFromHint("16L,34R", ""); got != "H16" {
		t.Fatalf("16L,34R → %q want H16", got)
	}
	if got := holdNameFromHint("34R", "A"); got != "H34" {
		t.Fatalf("34R → %q want H34", got)
	}
	if got := holdNameFromHint("", "B2"); got != "B2" {
		t.Fatalf("edge name → %q", got)
	}
}

func TestEncodeRejectsLegacyWithoutFlag(t *testing.T) {
	// parseFileVersion gate is in main; unit-test the threshold helper.
	if minXP12Version != 1200 {
		t.Fatalf("minXP12Version = %d", minXP12Version)
	}
	if parseFileVersion("1130 Generated by WED") >= minXP12Version {
		t.Fatal("1130 should be below XP12 minimum")
	}
}

func loadSnippetAirport(t *testing.T, snippet, wantID string) *rawAirport {
	t.Helper()
	var cur *rawAirport
	for _, raw := range strings.Split(snippet, "\n") {
		line := strings.TrimSpace(raw)
		if line == "" || line == "A" || line == "99" {
			continue
		}
		if parseFileVersion(line) > 0 || isFileVersionLine(line) {
			continue
		}
		fields := strings.Fields(line)
		if len(fields) == 0 {
			continue
		}
		if fields[0] == "1" || fields[0] == "16" || fields[0] == "17" {
			cur = parseAirportHeader(fields, line)
			continue
		}
		if cur == nil {
			continue
		}
		cur.Lines = append(cur.Lines, line)
		cur.Codes[fields[0]]++
	}
	if cur == nil || cur.ID != wantID {
		t.Fatalf("failed to load airport %s: %+v", wantID, cur)
	}
	return cur
}
